from pathlib import Path
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, Preformatted, Table, TableStyle
from reportlab.lib import colors
from reportlab.lib.units import mm

OUT=Path('output/pdf'); OUT.mkdir(parents=True,exist_ok=True)
styles=getSampleStyleSheet(); body=ParagraphStyle('body',parent=styles['BodyText'],fontSize=9.3,leading=11.5,spaceAfter=4); code=ParagraphStyle('code',parent=body,fontName='Courier',fontSize=7.2,leading=8.6); h=ParagraphStyle('h',parent=styles['Heading1'],alignment=TA_CENTER,fontSize=15,leading=18,spaceAfter=10)
def P(x,style=body): return Paragraph(x.replace('&','&amp;').replace('<','&lt;').replace('>','&gt;').replace('\n','<br/>'),style)

variants={
'A':[
('mcq','MCQ 1 and 2 are based on this code:\nint main() {\n  int a = fork();\n  printf("A %d\\n", a);\n  int b = fork();\n  printf("B %d\\n", b);\n  return 0;\n}\n\n1. How many lines are printed in total?\na. 2\nb. 3\nc. 4\nd. 6\ne. 8\n\n2. Which statement is always true?\na. Exactly two processes execute the second fork.\nb. The child of the first fork prints a non-zero value for a.\nc. Every process prints exactly one line.\nd. The two B lines have identical values.\ne. The program creates exactly three processes.'),
('mcq','3. A running process executes a blocking read on an empty pipe. Which transition occurs?\na. Running to Ready\nb. Running to Blocked\nc. Ready to Running\nd. Running to Terminated\ne. New to Ready\n\n4. A process performs getpid(), assuming the call does not block. What is its process-state transition?\na. Running to Blocked\nb. Running to Ready\nc. Running remains Running\nd. Running to New\ne. Ready to Terminated'),
('mcq','5. Which situation can produce priority inversion?\na. A high-priority task waits for a resource held by a low-priority task while a medium-priority task runs.\nb. Two high-priority tasks use different resources.\nc. A low-priority task waits for a resource held by a high-priority task.\nd. A medium-priority task terminates.\ne. A task performs only computation.\n\n6. Which is a typical microkernel disadvantage?\na. All services must run in kernel mode.\nb. User-space services cannot communicate.\nc. Extra IPC and context-switch overhead.\nd. Device drivers cannot be isolated.\ne. It cannot implement scheduling.'),
('mcq','7. A parent runs 240 ms of CPU work before fork(). The child runs 80 ms afterward and the parent runs 120 ms afterward. Under non-preemptive FCFS, with fork itself CPU-only, which process finishes first?\na. Child\nb. Parent\nc. They finish together\nd. Whichever has the larger PID\ne. Cannot be determined'),
('mcq','8. Which statement about a semaphore initialized to 3 is correct?\na. At most three processes can ever wait on it.\nb. At most three processes can be inside the protected section at once.\nc. Its value must become negative when a process waits.\nd. signal() decreases its value.\ne. wait() always blocks.'),
('mrq','9. Mark each statement True or False about context-switch overhead:\na. More saved CPU registers can increase the overhead.\nb. The number of user-level threads matters to a purely user-level thread switch performed without kernel involvement.\nc. A larger stack automatically means all stack contents are copied during every switch.\nd. Saving a process identifier takes time, but the number of children does not matter if only one parent PID is stored.'),
('mrq','10. Mark each statement True or False about IPC:\na. Shared memory usually requires explicit synchronization for shared writes.\nb. A pipe created by pipe() is normally unidirectional.\nc. Signals are suitable for transferring a large file.\nd. Message passing can require kernel involvement for each send/receive operation.'),
('mrq','11. Semaphore S starts at 2. Every process executes wait(S); section A; signal(S).\na. More than two processes may be blocked on S.\nb. At most two processes execute section A simultaneously.\nc. Section A must be a critical section.\nd. S can grow to 3 after repeated executions.'),
('mrq','12. Mark each statement True or False:\na. A system call may switch the CPU into kernel mode.\nb. A normal library function must always enter kernel mode.\nc. An empty program may still invoke exit-related OS code.\nd. A process can be ready without currently using the CPU.'),
('short','13. Non-preemptive SJF uses exponential prediction: New = α Actual + (1−α) Old. Processes A, B, C have predictions 160 ms, 120 ms, and 90 ms. B was blocked and just used 200 ms of CPU.\na. Find B’s new prediction for α=0.25.\nb. Which process is selected next?\nc. When should actual CPU usage be recorded?\nd. If workload phases change rapidly, should α be larger or smaller? Explain briefly.'),
('short','14. x starts at 50. Two processes execute concurrently. Determine all possible final values of x, and the minimum and maximum, for each case:\n(a) Both processes use the same binary semaphore initialized to 1:\n  wait(S); x=x+5; x=x-2; signal(S);\n(b) Process A uses S1 and process B uses S2; both start at 1, and each performs the same two updates without sharing a semaphore. Explain why the answer differs.'),
],
'B':[
('mcq','MCQ 1 and 2 are based on this code:\nint main() {\n  int p = fork();\n  printf("P %d\\n", p);\n  if (p == 0) fork();\n  printf("Q\\n");\n  return 0;\n}\n\n1. How many Q lines are printed?\na. 1\nb. 2\nc. 3\nd. 4\ne. 5\n\n2. How many processes exist immediately before termination?\na. 1\nb. 2\nc. 3\nd. 4\ne. 5'),
('mcq','3. A running process finishes main() and returns. Which transition occurs?\na. Running to Blocked\nb. Running to Ready\nc. Running to Terminated\nd. Running to New\ne. Ready to Running\n\n4. A running process spins in a busy-wait loop. Which is most accurate?\na. It necessarily becomes Blocked.\nb. It remains Running while it tests the condition.\nc. It becomes Terminated.\nd. It enters the New state.\ne. It releases every semaphore.'),
('mcq','5. Which setup permits priority inversion?\na. High and low tasks share a lock, and a medium task consumes CPU.\nb. High and medium tasks share no resources.\nc. Only one low task exists and it never acquires a lock.\nd. All tasks have equal priority.\ne. The high task terminates before requesting anything.\n\n6. Which statement about microkernels is most accurate?\na. Device drivers must be part of the kernel.\nb. Isolating services in user space can improve fault containment.\nc. IPC is unnecessary.\nd. They cannot support filesystems.\ne. They always outperform monolithic kernels.'),
('mcq','7. A parent has 150 ms of CPU work before fork(). After fork(), the parent needs 100 ms and the child needs 50 ms. Under non-preemptive FCFS, with fork CPU-only, who finishes first?\na. Parent\nb. Child\nc. They finish simultaneously\nd. The process with the lower PID always\ne. Not enough information'),
('mcq','8. Which statement about wait(S) and signal(S) is correct?\na. wait(S) releases a resource.\nb. signal(S) may wake a blocked process.\nc. wait(S) always succeeds immediately.\nd. signal(S) always blocks.\ne. A semaphore cannot have an initial value above 1.'),
('mrq','9. Mark each True or False:\na. A context switch may save and restore the program counter.\nb. Kernel-managed threads can affect scheduling overhead.\nc. Every byte in a process stack must be copied during a context switch.\nd. Storing a fixed-size process state means ten children necessarily cost ten times more to switch.'),
('mrq','10. Mark each True or False about system calls:\na. A system call is an interface to OS services.\nb. A pure arithmetic function necessarily causes a system call.\nc. System calls commonly involve a privilege-level transition.\nd. The OS can execute instructions on behalf of a process during a system call.'),
('mrq','11. S starts at 1. Each process executes wait(S); section A; signal(S).\na. At most one process is in section A at a time.\nb. An arbitrary number of processes may be waiting.\nc. S must become negative when there are waiters.\nd. If every wait has a matching signal, S cannot grow without bound.'),
('mrq','12. Mark each True or False about pipes and signals:\na. A pipe can be used for one-way byte-stream communication.\nb. Closing all write ends allows a reader to observe EOF.\nc. A signal normally carries an entire arbitrary data structure.\nd. A process that forgets to close a duplicated write end may prevent EOF.'),
('short','13. Exponential averaging uses New = 0.6 Actual + 0.4 Old. Ready processes A, B, C have predictions 180 ms, 140 ms, 100 ms. B was blocked and used 60 ms CPU.\na. Compute B’s new prediction.\nb. Which process is selected by non-preemptive SJF?\nc. When should the actual usage be measured?\nd. Explain why copying a running parent’s prediction to a new child may disadvantage other ready processes.'),
('short','14. x starts at 80. Process A performs x=x+3 twice; Process B performs x=x-4 twice. Each individual read-modify-write is non-atomic.\n(a) If both processes use one binary semaphore around both updates, find the possible final values.\n(b) If A and B use separate semaphores, find the possible final values and the minimum/maximum. State the key stale-register interleaving that creates an extreme value.'),
]}

def build(label,items):
 out=OUT/f'cs2106_midterm_variant_{label}.pdf'; story=[P(f'NATIONAL UNIVERSITY OF SINGAPORE<br/>SCHOOL OF COMPUTING<br/>CS2106: INTRODUCTION TO OPERATING SYSTEMS<br/>MIDTERM PRACTICE VARIANT {label}',h),P('Time Allowed: 1 Hour<br/>Answer all questions. Questions 1-8 are MCQ; questions 9-12 are multiple-response True/False; questions 13-14 are short-answer questions.'),Spacer(1,6)]
 n=1
 for kind,text in items:
  if kind=='short': story.append(P(text,body))
  elif kind=='mrq': story.append(P(text,body))
  else: story.append(P(text,body))
  story.append(Spacer(1,5)); n+=1
 doc=SimpleDocTemplate(str(out),pagesize=A4,rightMargin=16*mm,leftMargin=16*mm,topMargin=14*mm,bottomMargin=14*mm,title=f'CS2106 Practice Variant {label}')
 doc.build(story); print(out)
for k,v in variants.items(): build(k,v)
